#!/bin/bash
# {{{ Notes
#
# Notes:
#   1) 0 == false && 1 == true ... Duh!
#   2) Options are listed alphabetically only because I scan them faster.
#
# -------------------------------------------------------------------------- }}}
# {{{ Products to install.

base16ColorsFlag=0
desktopAppsFlag=0
echoConfigFlag=0
gitBashPromptFlag=0
kjvFlag=0
lunarVimFlag=0
myReposFlag=0
neovimBuildFlag=0
neovimPluginsFlag=0
osUpdateFlag=0
osUpdateKeysFlag=0
otherAppsFlag=0
pacmanPackagesFlag=0
pipPackagesFlag=0
rbenvFlag=0
removePersonalizationFlag=0
resolvFlag=0
rustFlag=0
sshDirFlag=1
sshHostKeyFlag=0
symlinksFlag=0
texPackagesFlag=0
tmuxPluginsFlag=0
vimPluginsFlag=0
wslFlag=1
yayPackagesFlag=0

# -------------------------------------------------------------------------- }}}
# {{{ Other variables used during product installation.

# The root personal repositories are cloned to.
cloneRoot=$HOME/git

# The email assiciated with git commit messages.
gitEmail="gary.a.howard@mac.com"

# Git user namn used for commit messages.
gitUserName="Traap"

# Ruby version to install.  rbenv is the Ruby enviornment manager.
# rubyVerion becomes the global Ruby version installed.
rubyVersion='3.2.0'

# Host name the Arch linux installation is known by.  The default host name
# is the Windows 10 or Windows 11 host name.
wslHostName=Zero
wslUserName="Knook"

# -------------------------------------------------------------------------- }}}
