#!/bin/bash
# {{{ Notes
#
# Notes:
#   1) 0 == false && 1 == true ... Duh!
#   2) Options are listed alphabetically only because I scan them faster.
#
# -------------------------------------------------------------------------- }}}
# {{{ Products to install. 

base16ColorsFlag=0
echoConfigFlag=0
gitBashPromptFlag=0
kjvFlag=0
myReposFlag=1
mySshRepoFlag=1
neovimBuildFlag=0
neovimPluginsFlag=1
osExtrasFlag=0
osUpdateFlag=0
rbenvFlag=0
removePersonalizationFlag=0
symlinksFlag=1
tmuxPluginsFlag=0
vimPluginsFlag=0

# -------------------------------------------------------------------------- }}}
# {{{ Other variables used during product installationl

cloneRoot=$HOME/git
gitEmail="gary.a.howard@mac.com"
gitName="Traap"
rubyVersion='3.0.2'

# -------------------------------------------------------------------------- }}}
