#!/bin/bash
# {{{ Notes
#
# Notes:
#   1) 0 == false && 1 == true ... Duh!
#   2) Options are listed alphabetically only because I scan them faster.
#
# -------------------------------------------------------------------------- }}}
# {{{ Products to install.

base16ColorsFlag=1
echoConfigFlag=1
gitBashPromptFlag=1
kjvFlag=1
myReposFlag=0
mySshRepoFlag=0
neovimBuildFlag=1
neovimPluginsFlag=1
osUpdateFlag=1
pacmanPackagesFlag=1
pipPackagesFlag=1
rbenvFlag=1
removePersonalizationFlag=0
resolvFlag=0
symlinksFlag=0
tmuxPluginsFlag=0
texPackagesFlag=1
vimPluginsFlag=0
wslFlag=0
yayPackagesFlag=1

# -------------------------------------------------------------------------- }}}
# {{{ Other variables used during product installation.

cloneRoot=$HOME/git
gitEmail="gary.a.howard@mac.com"
gitName="Traap"
rubyVersion='3.0.3'

# -------------------------------------------------------------------------- }}}
